services:
  neo4j:
    image: neo4j:5.5
    container_name: neo4j-test # Ensures this container has a unique name
    ports:
      - "7688:7687" # (avoids conflict with other Neo4j instances)
      - "7475:7474" # (avoids conflict with other Neo4j instances)
    environment:
      - NEO4J_AUTH=neo4j/testpassword
    volumes:
      - neo4j-test-data:/data
      - neo4j-test-logs:/logs
    healthcheck:
      test:
        ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpassword", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j-test-data:
  neo4j-test-logs:
