name: Build and Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          CI: true
        run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: ./TestResults