name: Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  wpf-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Download Neo4j
        run: |
          curl -L -o neo4j.zip https://neo4j.com/artifact.php?name=neo4j-community-5.5.0-windows.zip
          echo "Downloaded neo4j.zip"
          dir
          echo "Extracting Neo4j..."
          mkdir neo4j
          tar -xf neo4j.zip -C neo4j --strip-components=1
          echo "Extraction completed. Listing contents:"
          dir neo4j
          dir neo4j\bin

      - name: Start Neo4j
        run: |
          cmd /c "neo4j\bin\neo4j.bat install-service"
          cmd /c "neo4j\bin\neo4j.bat start"
        env:
          NEO4J_AUTH: "neo4j/testpassword"

      - name: Install dependencies
        run: dotnet restore

      - name: Run WPF tests
        env:
          CI: true
          NEO4J_AUTH: "neo4j/testpassword"
        run: dotnet test --filter Category=WPFIntegration
