name: CI Pipeline for ASTDiffTool

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up .NET SDK (Using .NET 8.0)
      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # Create appsettings.json using secrets
      - name: Create appsettings.json
        run: |
          echo "{
            \"Encryption\": {
              \"Key\": \"${{ secrets.ENCRYPTION_KEY }}\",
              \"IV\": \"${{ secrets.ENCRYPTION_IV }}\"
            },
            \"Neo4j\": {
              \"Uri\": \"${{ secrets.NEO4J_URI }}\",
              \"Username\": \"${{ secrets.NEO4J_USERNAME }}\",
              \"Password\": \"${{ secrets.NEO4J_PASSWORD }}\"
            }
          }" > D:\a\ast-diff-tool\ast-diff-tool\ASTDiffTool\appsettings.json
        shell: pwsh

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore
        env:
          EnableWindowsTargeting: true

      # Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Release
        env:
          EnableWindowsTargeting: true

      # Run tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        env:
          EnableWindowsTargeting: true

      # Clean up appsettings.json to remove sensitive information
      - name: Clean up appsettings.json
        run: Remove-Item -Path "D:\a\ast-diff-tool\ast-diff-tool\ASTDiffTool\appsettings.json" -Force
        shell: pwsh
